### ISSUE TITLE
Does not work on external storage.

### ISSUE THREAD

**Issue by JordanPlayz158** [ungoogled-software/ungoogled-chromium-android#100]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Moto G7
 - OS: LineageOS 18.1 (Android 11)
 - Arch: arm64
 - Variant: monochrome (I think it's monochrome, not really listed on the site so I will provide the download filename and option I chose to download from uc.droidware.info, ChromeModernPublic, SDK21 (iirc SDK29 wouldn't install at all))
 - Version: 92.0.4515.107
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes (I'd assume so)

**\*Describe the bug**
When trying to open Ungoogled Chromium when it's installed on external storage, it instantly closes upon opening.

**\*To Reproduce**
1. Download and Install the app.
2. Open it.

**\*Expected behavior**
The app should open (not instantly close) and work as it should on internal storage.

**Screenshots**
N/A

**Additional context**
Don't think this changes anything but I have TWRP installed as recovery and Magisk (root) flashed on the boot partition.

Main reason i'm making this an issue is that when I attempted to move the app to internal storage, the move button when clicked did nothing so it was not easy to get it on internal storage, had to go through adb shell and follow [this](https://stackoverflow.com/a/23283393).

**Comment by wchen342** [comment]
Two quick questions:
1. Does it work for vanilla chromium 92?
2. Is installing to external storage supported by stock OS?

I have never tried installing to external storage before so I don't know much about it. Generally Android is not very friendly with anything not in internal storage so a lot of things can happen.

**Comment by JordanPlayz158** [comment]
1. Could you point me to a download of chromium 92 for android, don't see it when searching for "chromium android apk" on SearX (or at least, don't see it from what i'd call "trustworthy sources")
2. Yes, I believe I could also move apps to sd card on my stock os as well and other apps work while on external storage so I think it is supported.

Most apps don't support external storage but it seems chromium or at least ungoogled chromium might have a prefer external flag or somthing as it installs by default to sd card when the install location value was set to 0 (auto, which I'd assume would mean the app should decide via flags like "preferExternal")

**Comment by wchen342** [comment]
You can get it here: https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Android%2F885299%2Fchrome-android.zip?generation=1621562340679855&alt=media

> it installs by default to sd card when the install location value was set to 0

I am not sure what you are referring to here? You mean the installing location set through ADB? Because there is no such setting I know that exists in code.

**Comment by JordanPlayz158** [comment]
> You can get it here: https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Android%2F885299%2Fchrome-android.zip?generation=1621562340679855&alt=media

Ok, will try out chromium to test.

> I am not sure what you are referring to here? You mean the installing location set through ADB? Because there is no such setting I know that exists in code.

I am referring to [this](https://developer.android.com/guide/topics/data/install-location). You can define whether you want your application installed on sd card ("preferExternal"), or let the system decide.

**Comment by JordanPlayz158** [comment]
I am sorry for taking so long to respond but the same issue occurs on chromium so it isn't on ungoogled chromium, my bad, should have tested before making an issue here

**Comment by wchen342** [comment]
No worries, you can go to the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/list) and reports there, maybe they can give some more information. Storage problems are quite hard to circumvent now since Google added Scoped storage in Android 10.

I will close this issue for now, if you have other problems feel free to open a new issue.
