### ISSUE TITLE
Migrate the old Chrome Duet flag to newer builds

### ISSUE THREAD

**Issue by allmeta** [ungoogled-software/ungoogled-chromium-android#102]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
i don't know where else to ask :'(

**Please describe the feature you would like to have**
In android it's hideous to stretch my fingers to the top of the screen to use the address bar or access options.
There used to be a flag for it in earlier builds of Chrome called Chrome Duet, but sadly it is removed.

**Describe the solution you'd like**
Either supporting the old flag or make ways to make a new flag with this functionality. 
I would also be happy if someone would point me to somewhere I can get started myself, as the chromium docs are pretty overwhelming.

**Describe alternatives you've considered**
Searched in issues and dabbled in the chromium source code

**Additional context**
Firefox vs ungoogled chromium for reference
Chromium:
![Screenshot_20211001_130642_org.ungoogled.chromium.stable.jpg](https://user-images.githubusercontent.com/22347443/135610528-187baee1-56da-47e2-bbec-9cdbb46fee5e.jpg)
Firefox:
![Screenshot_20211001_130623_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/22347443/135610543-ad91d95c-2c2c-48dc-ab46-a6e00093d02c.jpg)

**Comment by wchen342** [comment]
https://github.com/bromite/bromite/issues/667#issuecomment-668397131

I'm pretty sure the code no longer exists in chromium. Doing it new will require quite some work which I don't think I can do any time soon.

**Comment by th0mcat** [comment]
For those of you that want a bottom URL/toolbar again in Vanadium/Bromite a la Chrome Duet/Home, I think the best course of action is to have the code added upstream. With that in mind, I'd recommend staring this issue (https://bugs.chromium.org/p/chromium/issues/detail?id=1284380) on the Chromium issue tracker so the devs know this is a feature that a _lot_ of people would like to have again. Star is in the upper-lefthand corner.
