### ISSUE TITLE
Bromite patches

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-android#103]
Hi @csagan5, I haven't been able to apply `Add-bookmark-import-export-actions.patch` since cr93, build fails with

```
../../chrome/android/java/src/org/chromium/chrome/browser/bookmarks/BookmarkBridge.java:776: error: method initialize in class DownloadLocationCustomView cannot be applied to given types;
                mCustomView.initialize(
                           ^
  required: int,long
  found: int,File,int,String
  reason: actual and formal argument lists differ in length
../../chrome/android/java/src/org/chromium/chrome/browser/bookmarks/BookmarkBridge.java:781: error: cannot find symbol
                Resources resources = mContext.getResources();
                                      ^
  symbol: variable mContext
../../chrome/android/java/src/org/chromium/chrome/browser/bookmarks/BookmarkBridge.java:1271: error: cannot find symbol
            ((Activity)window.getContext().get()).runOnUiThread(new Runnable() {
              ^
  symbol:   class Activity
  location: class BookmarkBridge
```

The last one is easy to solve but the first error I am not sure where you get the extra parameters from?

**Comment by uazo** [comment]
you are right.

> The last one is easy to solve but the first error I am not sure where you get the extra parameters from?

we mixed changes between the `Add-menu-item-to-bookmark-all-tabs.patch` and the `Add-bookmark-import-export-actions.patch`.
thanks for the tip

@csagan5 I'll fix it if you agree

**Comment by csagan5** [comment]
@uazo please do; I also noticed something going on there.

**Comment by csagan5** [comment]
FYI the fix has already been merged.

**Comment by wchen342** [comment]
Looks good, thanks!
