### ISSUE TITLE
F-Droid repo does not properly allow update notifications

### ISSUE THREAD

**Issue by ltguillaume** [ungoogled-software/ungoogled-chromium-android#110]
**Device info (please complete the following information):**
 - Device: Samsung Galaxy S5
 - OS: LineageOS 17.1
 - Arch: ARM
 
**Describe the bug**
While I briefly mentioned this in #104 I feel like a separate issue should be created for this, since it doesn't seem to be resolved.

For _any_ of the updates coming out via the F-Droid ARM repo, I _have_ to manually check for updates under the Versions header: F-Droid will _never_ notify me of any updates, nor will will it consider listing newer versions as updates. The most probably cause for this is that none of the new versions available are ever marked as stable, so users will only be notified of new versions if they enable the expert option "Unstable updates".

This doesn't seem to be documented anywhere as the desired behavior, so I'm assuming this is an oversight.

**Comment by wchen342** [comment]
Interesting, thanks for the observation. Unfortunately the documentation of f-droid server tool is basically non-exist and I never knew there is a setting that I can change for marking packages "stable" or not. I will see whether I can somehow find the property and change how their script write the server xml files.

**Comment by ltGuillaume** [comment]
I agree, F-Droid documentation _and_ support is a mess: there's a lot of it, but it's fragmented and nothing is specific enough.

**Comment by ltGuillaume** [comment]
The F-Droid repo hasn't been updated for a month, how come?

**Comment by wchen342** [comment]
You can use Tobi823's great [ffupdater](https://github.com/Tobi823/ffupdater) to get releases directly from Github, it is the fastest way. I was a little busy after the holiday and also had some other commitments so the release got delayed a bit.

> I can't check if the problem described here

No worries, I have F-Droid client on my phone and I can check myself.

**Comment by NKentatE** [comment]
@wchen342 would you please fix the issue?

**Comment by PF4Public** [comment]
Unfortunately F-Droid repo no longer functions.
