### ISSUE TITLE
Clear cookies on exit

### ISSUE THREAD

**Issue by nandlab** [ungoogled-software/ungoogled-chromium-android#111]
On previous ungoogled-chromium-android versions (e.g. `88.0.4324.182`, the last one with extension support) you could enter the url `chrome://settings/` and in `Privacy and security -> Cookies and other site data` you could enable `Clear cookies and site data when you quit Chromium`.
I cannot see any option to clear cookies in version `96.0.4664.110`. If I type `chrome://settings/` it shows the error `ERR_INVALID_URL`.
Was this feature removed in the official chromium for android or is there any other setting I miss out?

**Comment by wchen342** [comment]
That option only exists on desktop versions of `ungoogled-chromium`. The extension version ported the desktop setting page as a by-product of extension support, that is why you can open `chrome://settings/` on that version. Now without extension support that page is gone too.
I can add a new switch under `Privacy and security` for this specific option.

**Comment by NANDLAB** [comment]
That would be awesome!

**Comment by ltGuillaume** [comment]
That would be great indeed!

**Comment by wchen342** [comment]
I just tested the desktop flag on Android, it actually doesn't work even if the flag is enabled. I think that shall also be the case in the extension version, can you please test it?

**Comment by wchen342** [comment]
Added in d00916d.
