### ISSUE TITLE
Just a request for "uninstall" info/documentation for the *Library* apk.

### ISSUE THREAD

**Issue by jaimet** [ungoogled-software/ungoogled-chromium-android#120]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: OnePlus 5T
 - OS: OxygenOS v10.0.1 (Android 10/Android Q)
 - Arch: arm64
 - Variant: Non-extension version
 - Version: 97.0.4692.71
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
n/a

**\*Describe the bug**
I read the [README](https://github.com/ungoogled-software/ungoogled-chromium-android/blob/master/README.md) but I find no information about uninstalling the Library apk. (Obviously, the "app" is easy to uninstall - just go to the app list on my phone, find "Ungoogled Chromium", select it then click "Uninstall" - but the Library apk is listed nowhere).

I found the following info [here](https://github.com/ungoogled-software/ungoogled-chromium-android/issues/83#issuecomment-812557480):

`adb shell 'dumpsys package | grep "Package \["' | grep trichromelibrary`
You shall get a package name like org.chromium.trichromelibrary_[some random number].
`adb uninstall org.chromium.trichromelibrary_[the random number]`

Is this the **_only_** way to uninstall the Library apk, or is it possible to uninstall the Library apk **_without_** using adb?

Either way, could you please add a note to the [README](https://github.com/ungoogled-software/ungoogled-chromium-android/blob/master/README.md) to explain how to uninstall the Library apk? Thank you

**Comment by jaimet** [comment]
Just extra info in case it helps. The following returns the package name required for the `adb uninstall <package>` command:

(from an `adb shell` command prompt:)
```
dumpsys package | \
grep '^  Package \[org.chromium.trichromelibrary' | \
awk -F '[][]' '{print $2}'
```

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
