### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by OrdinaryUser13** [ungoogled-software/ungoogled-chromium-android#121]
There's an issue that has been there since forever...Some Apps that require webview to run and a log in on an account crash for no apparent reason!
I can name a few apps you can test.
Grepolis---game crashes after first splash screen
Mobile Legends--Can't log in as webview crashes midway when app is trying to open the login page and just freezes
Ymusic---Doesn't let it's player start playing a song due to webview crashes.
I hope you can revisit and have a clue of what's happening

**Comment by fohfuu** [comment]
There's a lot more information you need to give before anyone can say what's causing this. Please close this issue and make a new one following the bug report template. If you ignore it, you won't get a response.

**Comment by PF4Public** [comment]
This is an old issue, that didn't show much activity recently — closing.
If you have any more information to add, let us know.
