### ISSUE TITLE
F-Droid repo update? 

### ISSUE THREAD

**Issue by neekless** [ungoogled-software/ungoogled-chromium-android#123]
Does the f-Droid repo not fetch the apks from github? The version in the repo is stuck at 97.0.4692.71

**Comment by fohfuu** [comment]
Can you check under "Versions" on F-Droid and screenshot/write which versions are available? Also, which specific repository?

It updated to 99.x for me months ago on the arm64 repo.

**Comment by wchen342** [comment]
I won't be able to update the versions for some time. If possible please use one of the browsers listed [here](https://github.com/Tobi823/ffupdater#firefox-updater) in the meantime.

**Comment by Andronx** [comment]
Looks like F-Droid repos are gone. Someone has working links?

**Comment by fohfuu** [comment]
@Andronx, if you really want to access the previous versions of UC, you can download them from the Releases section. I really advise you don't use it as a browser, though, as browsers need to be constantly updated for security patches, and this hasn't been updated since March.

Bromite is pretty close to UC in most aspects, if you want a recommendation for a  replacement.

**Comment by PF4Public** [comment]
> Looks like F-Droid repos are gone. Someone has working links?

@Andronx  How have you come to that conclusion? Looks functioning for me:
![Screenshot_20221010-210930](https://user-images.githubusercontent.com/10319700/194929101-1af81fd8-d80e-46e9-9c55-1c112d44da37.png)

Also see https://github.com/ungoogled-software/ungoogled-chromium/pull/2039

**Comment by Andronx** [comment]
@PF4Public, My mistake, I opened links on pc web browser and and saw 403 Forbidden, then I searched "ungoogled" in f-droid and obvious result was nothing. I forgot that I suposed to just add repo from link to f-droid app :).

**Comment by 0-Rainer-Stoff-0** [comment]
> Does the f-Droid repo not fetch the apks from github? The version in the repo is stuck at 97.0.4692.71

**Comment by PF4Public** [comment]
@0-Rainer-Stoff-0 Short answer is No.

**Comment by PF4Public** [comment]
Unfortunately F-Droid repo no longer functions.
