### ISSUE TITLE
Can i install ublock origin on this browser since there's MIME flag?

### ISSUE THREAD

**Issue by mycal123** [ungoogled-software/ungoogled-chromium-android#124]
I have seen and used old discontinued repository of ungoogled chromium  extension support.

I found a closed which is talking about UBO extension installation on this repository.

.....
I'm asking after enabling MIME promt install flag but found no install button on cws and chrome://extension is not found in chrome url list.

**Comment by PF4Public** [comment]
Extensions are not supported on Android. You might try installing no longer supported version of ungoogled-chromium, that supports extensions, but it is last updated at chromium 89 IRC.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.
