### ISSUE TITLE
gn not found

### ISSUE THREAD

**Issue by chunsun21** [ungoogled-software/ungoogled-chromium-android#126]
I followed the Building Instructions.
But, I encountered error message.

./build.sh: line 319: gn: command not found

or

gn.py: Could not find gn executable at: [dir_path]/ungoogled-chromium-android/src/buildtools/linux64/gn

Is there any guidance?
Thanks.

**Comment by wchen342** [comment]
You need to have gn installed on your system. On debian the package name is `generate-ninja` and on Arch it is `gn`.
