### ISSUE TITLE
Me repo


### ISSUE THREAD

**Issue by Koshvild08** [ungoogled-software/ungoogled-chromium-android#128]

**Comment by PF4Public** [comment]
What is this all about?

**Comment by wchen342** [comment]
Just some random spam. Why the repo is unarchived btw?

**Comment by PF4Public** [comment]
> Why the repo is unarchived btw?

It never was AFAIK. Yours is : https://github.com/wchen342/ungoogled-chromium-android

**Comment by wchen342** [comment]
@PF4Public That's weird, I should have archived this one and Fedora repo. Anyway I'll just do that again.
