### ISSUE TITLE
Unable to build chromium with extension

### ISSUE THREAD

**Issue by Oopas** [ungoogled-software/ungoogled-chromium-android#131]
I try to use the relevant files of the `extensions` branch to build chromium.

Some files specified in build.sh have to be replaced because the target website is closed. I replaced it with a new version of the file you shared(e.g. sdk ndk...)

After I finally used llvm 13 and fixed one or two syntax errors in the official source code, I successfully obtained `ChromeModernPublic.apk`(target: chrome_modern_public_bundle)

But when I click the chromium store icon in the menu bar, it does not work like `v88.0.4324.182-2-Extensions` you published in `Releases,` but displays as a blank interface.....

![Screenshot_2022-11-22-13-29-33-151_org ungoogled chromium extensions stable](https://user-images.githubusercontent.com/69417818/203230704-f0722c4e-365c-47c5-9921-8777cb40b504.jpg)

although `chrome://extensions` It looks normal, but when I try to download the plug-in from the chrome store, I find it has no download button......

![Screenshot_2022-11-22-13-32-55-029_org ungoogled chromium extensions stable](https://user-images.githubusercontent.com/69417818/203231818-be7417ad-5db9-42f7-8651-b9c8125be3c4.jpg)

I also tried your project before this: [chromium-android-extension](https://github.com/wchen342/chromium-android-extension) 

But unfortunately, it broke down as soon as it was opened.

Hope to get some help😫

**Comment by PF4Public** [comment]
> it has no download button......

AFAIK download button is provided by yet another extension: https://github.com/NeverDecaf/chromium-web-store

**Comment by Oopas** [comment]
> > it has no download button......
> 
> AFAIK download button is provided by yet another extension: https://github.com/NeverDecaf/chromium-web-store

When I tried to compile, it reported an error and the file was missing. Later, I downloaded the latest version of the project to the corresponding directory in chromium, so it can successfully complete the compilation.

Earlier today, I tried to use the version of this project(v1.2.2) released on the same day as `v88.0.4324.182-2-Extensions`. It seems that this problem has been solved(likely).

Although the download button is only a pure blue color block, it can still be installed normally.

Now the only question left is the blank question displayed after clicking the Chromium Store icon from the menu bar (it doesn't seem to be a question)

**Comment by PF4Public** [comment]
Have you tried installing any other extension besides Web Store?

**Comment by Oopas** [comment]
> 

It seems that there is no problem with the use of plug-ins.

However, I'm not sure whether it is the plug-in version that cannot be used before.

My last question is, do you know where the chromium logo for apk is located in the source code?

**Comment by PF4Public** [comment]
> My last question is, do you know where the chromium logo for apk is located in the source code?

No idea
