### ISSUE TITLE
How Do I Take Advantage Of Cash App Direct Deposit Facility?

### ISSUE THREAD

**Issue by adenjaxson** [ungoogled-software/ungoogled-chromium-android#132]
Are you one of those users who are looking to enable the direct deposit feature to deposit paychecks on Cash App? Aren’t you aware of the required procedure to enable the same facility to enjoy all its features and benefits without any kind of hassle? To do so, you should first go to the help section of Cash App where the proper procedure of enabling the Cash App Direct Deposit (link redacted for scamming) feature is discussed comprehensively in a proper and hassle-free manner.

**Comment by networkException** [comment]
Note to self: Report user, cant do this from mobile
