### ISSUE TITLE
[Urgent Question] Extensions branch of the Ungoogled Chromium Project for Android

### ISSUE THREAD

**Issue by joeyoropesa-dev** [ungoogled-software/ungoogled-chromium-android#138]
Can this project continue with the work or we're all forced to move to the Kiwi Browser or other browsers with chrome extensions support that getting chromium base updates. The latest update in Extensions branch was 2021 and that's literally too old for 2023 so... can we know what's going on?

Is it the owner of the project give to us annoucement is this discontinued project or not.

Thanks in advance for your response!

**Comment by PF4Public** [comment]
> Can this project continue with the work

It was an experiment without any promises to begin with

>can we know what's going on?

No one maintains ungoogled-chromium-android since Mar 2022.

**Comment by joeyoropesa-dev** [comment]
> > Can this project continue with the work
> 
> It was an experiment without any promises to begin with
> 
> >can we know what's going on?
> 
> No one maintains ungoogled-chromium-android since Mar 2022.

I know - that's why I'm afraid and why I created this issue - it's urgent.


The only project that was very closer to pure Google Chrome/Chromium was this project and it would be sad that we will not see it ever again in our lifes. Every other projects, including Kiwi Browser have their own branding, home page and many other things provided by official Chromium code base was replaced by their code so it's not anymore an pure Chromium project with chrome extensions on Android.


That's why this project is so special - it's the only one project that is like I explained. There is no other projects like this. If the dev could at least make the public-accessible workflow that can be run in forked repositories so that we can always update the project to the latest Chromium base and always compile it with one button without re-coding it manually, it would be very cool and the ungoogled chromium would be able to still exist and be refreshed always.


With ability to update the chromium base and use chrome extensions android build patches, everything could be possible again.


But someone behind all this needs to agree with this and make that wonderful file with built-in codes and commands that can do all this without messing up with the code itself every time when we need the chromium base update in this project.

**Comment by PF4Public** [comment]
I hope your question(-s) has(-ve) been answered, otherwise please let us know.
Closing this issue for now.

**Comment by joeyoropesa-dev** [comment]
> I hope your question(-s) has(-ve) been answered, otherwise please let us know.
> Closing this issue for now.

so... there is nothing that maybe you can do? Only giving up and let this project to die forever?

**Comment by PF4Public** [comment]
To be completely honest I did consider many times to continue ungoogled-chromium-android, but unfortunately to date couldn't find enough time I could dedicate to maintaining it.

I don't want to give you false hopes, so please do not raise your expectations, maybe someday I will have enough time.
