### ISSUE TITLE
Native crash - HTTPS everywhere

### ISSUE THREAD

**Issue by unixandria-xda** [ungoogled-software/ungoogled-chromium-android#22]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: OnePlus 7 Pro
 - OS: BlissROM 12.8 (sdk29)
 - Arch: arm64
 - Variant: monochrome
 - Version: 83.0.4103.106
 
**\*Is the bug related to extensions?**
Yes

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
Https everywhere settings button under extensions options in chrome://extensions leads to a native crash
https://del.dog/peehefifox

Full logcat: https://transfer.sh/C0dbO/logcat_06-23-2020_23-41-48.txt

**\*To Reproduce**
1. Go to extensions page for https everywhere
2. Click on extensions option
3. Click settings

**\*Expected behavior**

Doesn't crash the browser 

**Screenshots**

**Additional context**

**Comment by wchen342** [comment]
Moast likely because of some UI pop up. Will investigate.

**Comment by wchen342** [comment]
Fixed with 2058c63.
