### ISSUE TITLE
Crash on trying to remove extensions 

### ISSUE THREAD

**Issue by cleanerspam** [ungoogled-software/ungoogled-chromium-android#25]
Chrome-84.0.4147.105
32bit
Android 10 
When I try to remove an extension from `chrome://extensions` the browser freezes and then crashes(it happens frequently but sometimes it does not crash and when I reload the extension has been successfully removed)
[2020-08-06-06-44-00.txt](https://github.com/ungoogled-software/ungoogled-chromium-android/files/5031956/2020-08-06-06-44-00.txt

Also when I try to disable an extension the switch state remains same until I reload the page

**Comment by wchen342** [comment]
Which extension has problem with removing? Is the log file a mixture of multiple runs, and I also see kiwi at the end?

I am aware of the reload problem. Somehow it doesn't automatically happen on Android.

**Comment by cleanerspam** [comment]
> Which extension has problem with removing? Is the log file a mixture of multiple runs, and I also see kiwi at the end?
> 
> I am aware of the reload problem. Somehow it doesn't automatically happen on Android.

All extensions were having this problem but somehow after I cleared cache of app and restarted browser it stopped crashing on trying to remove extensions although the autorefresh ( reloading) problem is still there
