### ISSUE TITLE
Request Desktop site error 

### ISSUE THREAD

**Issue by cleanerspam** [ungoogled-software/ungoogled-chromium-android#26]
**\*Device info (please complete the following information):**
 - Device: [ Asus X00t]
 - OS: [AOSP android 10]
 - Arch: [arm]
 - Variant: [extension]
 - Version: [ 84.0.4147.105]
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
When I enable desktop site on a site that I visited using duckduckgo.com instead of loading the site in desktop mode it reloads the previous page I.e.the search results and then I have to again navigate to my desired web site

**\*To Reproduce**
1. Set duckduckgo as default
2. Search "ublock chrome"
3. Open the first result (opens in mobile view )
4. Turn on desktop mode 
5. Browser goes back to duck result page and opens it in desktop mode 

**\*Expected behavior**
It should reload the current webpage in desktop mode .

**ScreenRecord**
![Screenshot_20200806-075853426__01](https://user-images.githubusercontent.com/59386233/89483936-e8551380-d7ba-11ea-8488-7b6ae38a1811.jpg)

[Video (mediafire)](https://www.mediafire.com/file/em7sdfp6efpzv66/ScreenRecord-20200806-071827_01.mp4/file) 

**Additional context**
Only happened on DuckduckGo does not happens when google is default search provider

**Comment by wchen342** [comment]
If this happens with plain chromium then it is not a ungoogled chromium bug.

**Comment by wchen342** [comment]
Also I don't have `84.0.4044.138` as a version. Is that from `Bromite`?

**Comment by cleanerspam** [comment]
> Also I don't have `84.0.4044.138` as a version. Is that from `Bromite`?

Sorry
 I forgot to change the whole version number of issue template 
Updated Now with correct info

**Comment by wchen342** [comment]
So does it happen with plain Chromium exactly?

**Comment by cleanerspam** [comment]
> So does it happen with plain Chromium exactly?
It does not happens on Chromium 
Checked on version 84.0.4147.127

**Comment by wchen342** [comment]
So turns out it happens with non extension version too. Probably some problem with the patches from main repo.

**Comment by wchen342** [comment]
It is related to the flag `fieldtrial_testing_like_official_build=true`. But I need to figure out why before I can remove the flag.

**Comment by wchen342** [comment]
Ok I figured out the fix is to enable a feature called `ProactivelySwapBrowsingInstance`. According to the comments there should be no downside of enabling this, except for probably some small increase in memory usage.

**Comment by wchen342** [comment]
Resolved in 1812d02.
