### ISSUE TITLE
CPU and Version usage poll

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-android#28]
For personal reasons I am going to lose my current computational power starting as early as this October. I will try to figure out whether I can use OBS to compile the apks but at the mean time I *may* have to reduce the number of variants I pre-compile for users.
I want to make a poll to know which variants are used most by current users in advance.

Please **DO NOT** reply but vote by clicking "+1" for the corresponding variant you are using below. I will see the results and decide which variants to keep providing as apks.

**Comment by wchen342** [comment]
CPU: arm (32-bit)
Version: ChromePublic (Android 21+)

**Comment by wchen342** [comment]
CPU: arm64 (64-bit)
Version: ChromePublic (Android 21+)

**Comment by wchen342** [comment]
CPU: arm (32-bit)
Version: MonochromePublic (Android 24+, Nougat and later)

**Comment by wchen342** [comment]
CPU: arm (64-bit)
Version: MonochromePublic (Android 7.0, Nougat and later)

**Comment by wchen342** [comment]
CPU: x86 (32-bit)
Version: ChromePublic (Android 5.0, Lollipop and later)

**Comment by wchen342** [comment]
CPU: x86 (32-bit)
Version: MonochromePublic (Android 7.0, Nougat and later)

**Comment by varbhat** [comment]
CPU: arm64 (64-bit)
Version: ChromePublic-extensions

**Comment by wchen342** [comment]
No need to vote for extension version since there is only one extension version.

**Comment by gerroon** [comment]
CPU: Arm
Version: Nougat and above (SDK24)

**Comment by wchen342** [comment]
Please **DO NOT** reply but use "+1" instead.

**Comment by csagan5** [comment]
@wchen342 as far as I know ChromePublic should not be used on Android 5.0 as you would miss some important functionality, including security ones; that is because it is built with a backward-compatible previous SDK.

**Comment by wchen342** [comment]
@csagan5 How do you support 5.0~7.0 then? I think Monochrome won't run on 5.0, or it runs but with less functionalities?

**Comment by csagan5** [comment]
> I will try to figure out whether I can use OBS to compile the apks

I cannot share my build server for security reasons but @wchen342 you could easily find someone willing to offer the compute resources. Just from a random search: https://www.digitalocean.com/open-source/

There are many others (mostly big ISPs/cloud providers) which would be willing to offer a VPS in exchange of a mention link somewhere. We may even ask about this in coordination for both projects (Bromite and ungoogled-chromium-android), I have some experience with open source projects.

**Comment by wchen342** [comment]
@csagan5 Interesting, didn't know cloud providers are providing free computational resources. I am open to cooperations since I am much less experienced about these stuffs. If youo have something in mind just let me know.

**Comment by csagan5** [comment]
> How do you support 5.0~7.0 then? I think Monochrome won't run on 5.0, or it runs but with less functionalities?

From https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md#multiple-chrome-targets it says now that ChromPublic is the same as ChromeModernPublic; but for v84 and below it was different: https://github.com/chromium/chromium/blob/84.0.4147.132/docs/android_build_instructions.md#multiple-chrome-targets

As you can see it mentions that SDK is 19 for ChromePublic; that is useless on Android 5.0 and above.

**Comment by csagan5** [comment]
> Interesting, didn't know cloud providers are providing free computational resources. I am open to cooperations since I am much less experienced about these stuffs. If you have something in mind just let me know.

I will send some emails and let you know; DigitalOcean actually does not seem that interesting, see https://docs.google.com/document/d/1P1ZqpxgKtiNibtWs53dLeCBmfp47Nqi6QlRg74lbsAc/edit (I will not ask them any sponsorship).

**Comment by padaki-pavan** [comment]
CPU: arm64 (64-bit)
Version: MonochromePublic (Android 7.0, Nougat and later)

**Comment by wchen342** [comment]
@Eloston Is there any update on the build server searching?

**Comment by Eloston** [comment]
@wchen342 Right now, I am waiting for a response from Gandi. I am planning on sending a followup this week.

Are you still projected to lose your build resources by October?

**Comment by wchen342** [comment]
> Are you still projected to lose your build resources by October?

Actually it is confirmed now. I will build `85.0.4183.121` this weekend and after that I will pause release for a month, both for losing of computational resource and my moving to a new country. After that I will at least have a laptop to develop but building multiple versions will be very time demanding. I am going to post a notice on the website of Android version for this.

**Comment by TheJags** [comment]
CPU: arm64 (64-bit)

Version: **Extensions** Chrome Modern Public arm

**Comment by Niek** [comment]
CPU: x86
Version: ChromePublic (Android 5.0, Lollipop and later)

**Comment by wchen342** [comment]
Closing for now for building servers provided by [Gandi.net](https://www.gandi.net/).
