### ISSUE TITLE
Automatically open Chrome Web Store in Desktop mode

### ISSUE THREAD

**Issue by cleanerspam** [ungoogled-software/ungoogled-chromium-android#29]
**Please describe the feature you would like to have**

Whenever I want to install an extension I generally use Chrome Web Store but since it recognizes my browser UA as that of mobile it does not allow installing extensions and so I have to manually request desktop site .

**Describe the solution you'd like**
Automatically open Chrome Web Store in Desktop Mode

**Describe alternatives you've considered**
Not being lazy

**Additional context**
Kiwi browser has this feature 
![Screenshot_20200817-200920__01](https://user-images.githubusercontent.com/59386233/90408595-a9319700-e0c5-11ea-9762-df842502396a.jpg)

**Comment by wchen342** [comment]
This is not as easy as it looks. I will keep this open but do not expect it to happen very soon.

**Comment by NSTAdventure** [comment]
Yay! 🤟
