### ISSUE TITLE
[Feature Request] Save-Data: on setting

### ISSUE THREAD

**Issue by BasilTomato** [ungoogled-software/ungoogled-chromium-android#32]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
This feature is built-in the Chrome Android browser, but can not be set in Ungoogled Chromium Android. Or at least I was not able to find any information regarding this.

**Please describe the feature you would like to have**
Would it be possible to support the "Save-Data: on" HTTP request header for potential data saving on mobile data connection?
It is supported in the Chrome Android app "Lite mode" (previously: "Data Saver"), but the lite mode itself is removed from Ungoogled Chromium Android thus the save-data request also removed.

**Describe the solution you'd like**
Setting this HTTP request header via flag or other means.

**Describe alternatives you've considered**
n/a

**Additional context**
Background information: https://www.ctrl.blog/entry/http-save-data.html

**Comment by wchen342** [comment]
The feature will route all your traffic through Google's servers which is not supposed to happen in ungoogled-chromium.

**Comment by BasilTomato** [comment]
As far as I understand this is a HTTP request header field independent from the Chrome Lite mode feature, or any specific browser features.

The article above describes the background and links a Firefox extension created by the article's author.

**Comment by BasilTomato** [comment]
Source code of the extension itself: https://github.com/da2x/save-data/blob/master/background.js

**Comment by wchen342** [comment]
Oh you meant the header not the lite mode feature. I see.

**Comment by wchen342** [comment]
Added in 81966c5.
