### ISSUE TITLE
allow native autofill service support

### ISSUE THREAD

**Issue by flesti** [ungoogled-software/ungoogled-chromium-android#35]
As described here: https://github.com/Kunzisoft/KeePassDX/issues/769
Seems that Chrome /Chromium (?) no longer supports native autofill, that makes 3rd party password apps almost impossible to work.

**Comment by wchen342** [comment]
This is an upstream problem which I cannot fix on my own since it involves Android system services. If Bromite manage to create a patch I can adapt it, otherwise needs to wait for Chromium to fix it.
