### ISSUE TITLE
Enabling "chrome://flags/#extensions-toolbar-menu"

### ISSUE THREAD

**Issue by pezlaf** [ungoogled-software/ungoogled-chromium-android#37]
Some extension functionalities are inaccessible due to the "extensions-toolbar-menu" flag being listed as "not available for your platform".
I don't know how difficult it is to activate this, but it would be really great to have it.

**Comment by wchen342** [comment]
Do you mean mean the icons for extensions? That is #21. Toolbar in the context of extensions is actually a different concept.

**Comment by pezlaf** [comment]
Hi,
You are totally correct! I was confused.
Thanks for your work on this project!
