### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#38]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Add Feature To Export Bookmark 

**Please describe the feature you would like to have**
Export Import Bookmark Just Like Google Chrome

**Describe the solution you'd like**
I Want To Backup The Bookmark :-(

**Describe alternatives you've considered**
No Alternative only export import Bookmark

**Additional context**
No Screenshot Available

**Comment by wchen342** [comment]
There is an option to import/export bookmarks in the menu on bookmark page. Unless you have [this problem](https://github.com/bromite/bromite/issues/831) otherwise it should work.

**Comment by NSTAdventure** [comment]
Closed 
Resolved 

Thank You @wchen342
