### ISSUE TITLE
Incompatibility question

### ISSUE THREAD

**Issue by AlexKalopsia** [ungoogled-software/ungoogled-chromium-android#39]
Hi,

I run Android 11 on my Xperia 1II. F-Droid labels the app as incompatible, I am curious why that is the case and what I can do to get the app to run on my phone.

Thanks

**Comment by wchen342** [comment]
Theorically it shall run fine. The incompatible note comes from the problem that the f-droid server tool I use to generate the repo has a moximum API level of 29 which is Android 10. Maybe I will try to modify those scripts to circumvent this next time.

**Comment by wchen342** [comment]
Strange, I checked the metadata generated and it says `targetSdkVersion` is 30, so probably this is not the problem.
Can you use expert mode in fdroid client and see what version the client says you need to be on?

**Comment by AlexKalopsia** [comment]
Mmm just so you know today I checked and there was no incompatible label anymore. I could install v87.0.4280.141

**Comment by wchen342** [comment]
Ok so I assume this is solved.
