### ISSUE TITLE
Shortcut won't work

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#40]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Realme 5i
 - OS: Realme UI Android Q
 - Arch: Arm64
 - Variant: 
 - Version: 
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes

**\*Describe the bug**
If you add some website to home screen you can't use the shortcut to re visit the web Doing so will result nothing

**\*To Reproduce**
1. Open ungoogled Chromium 
2. Visit one web site (ex: google.com)
3. Tap 3 dots on the right and click add to home screen
4. Now try to launch it from home screen and there is nothing happend

**\*Expected behavior**
Is should work :-/

**Screenshots**

**Additional context**
Using v86.0.4240.111
for this test idk support extension or not i din't check changelog properly :-/

**Comment by wchen342** [comment]
Sounds like a general problem unrelated to extension. Will investigate.

**Comment by NSTAdventure** [comment]
> Sounds like a general problem unrelated to extension. Will investigate.

...

**Comment by NSTAdventure** [comment]
@wchen342 
Hey from where this connection coming?why it's on ungoogled Chromium latest version?
https://dnslytics.com/whois-lookup/ff02::2

**Comment by wchen342** [comment]
Is it [this](https://github.com/Eloston/ungoogled-chromium/issues/1297)?

**Comment by wchen342** [comment]
It works on my phone so I cannot debug it locally. Can you post your `adb logcat` output when you hit the icon?

**Comment by NSTAdventure** [comment]
> It works on my phone so I cannot debug it locally. Can you post your `adb logcat` output when you hit the icon?

Wait
In my phone are working too!
I think this uc bug on version:
V86 blah i forgot which one i check it later

**Comment by NSTAdventure** [comment]
@wchen342
Sorry for OOT
Setting on chrome flag can be imported?

**Comment by wchen342** [comment]
No.

**Comment by NSTAdventure** [comment]
> No.

Pls add it on next update import export if possible
Thanks

**Comment by wchen342** [comment]
That is not possible even on desktop version. If you open an issue on this in the [main repo](//github.com/eloston/ungoogled-chromium) maybe others can give more suggestions, but AFAIK it is not possible.

**Comment by NSTAdventure** [comment]
> That is not possible even on desktop version. If you open an issue on this in the [main repo](//github.com/eloston/ungoogled-chromium) maybe others can give more suggestions, but AFAIK it is not possible.

Ok this is one reason why i hate google 🤣🤦
