### ISSUE TITLE
Not Effective To Block Google

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#41]
Based On My Tracker Control App Ungoogle Chromium Still Able To Contact Google Though...
![Screenshot_2021-01-15-13-19-31-57](https://user-images.githubusercontent.com/50813528/104688993-591e3580-5734-11eb-86fc-a3ed66643a3d.jpg)

MAMAMIA NO! 🥴

**Comment by wchen342** [comment]
The new version hasn't been released yet.

Also those extra domains (Amazon, etc.) come from the websites you visited not UC itself. You need to test by clearing the historical recorded domains and without visiting anysite using Google/Amazon/etc.

**Comment by NSTAdventure** [comment]
@wchen342 
Uh.....
Other domain for preference only 
I open new issues about this later

**Comment by wchen342** [comment]
What do you mean? UC doesn't block the trackers on websites you visit, it only makes sure the browser itself doesn't connect to Google.

**Comment by NSTAdventure** [comment]
> What do you mean? UC doesn't block the trackers on websites you visit, it only makes sure the browser itself doesn't connect to Google.
> 
> Edit: if you want a chromium based browser with internal ad blocker, see [bromite](github.com/bromite/bromite).

O yeee and Ungoogled Chromium did :) 
They still connect to google
Fonts.gstatic.com

**Comment by wchen342** [comment]
Can you describe exactly what you did step by step and what you see?
I cannot know what was going on with such a vague description.

**Comment by NSTAdventure** [comment]
Download and install TC 
Activate VPN using TC
Open Ungoogled Chromium
Visit Website Like Github And Check The Log On TC
(TC=Tracker Control)

**Comment by wchen342** [comment]
As I said above, UC doesn't block connections to Google *if you visit websites using Google assets*. It is not a tracker blocker, i.e. it does not do what uBlock Origin does.

**Comment by NSTAdventure** [comment]
> This does not mean it will block _all_ connections if you are browsering a website that will connect to Google itself.

But if you din't block them when visit website
Google still can track you :) 
Google analytic bruh

**Comment by wchen342** [comment]
That is not the goal of this browser. I suggest you read [objectives](//github.com/Eloston/ungoogled-chromium#objectives).

**Comment by NSTAdventure** [comment]
> That is not the goal of this browser. I suggest you read [objectives](//github.com/Eloston/ungoogled-chromium#objectives).

But in objective:
googled-chromium features tweaks to enhance privacy
.........

**Comment by wchen342** [comment]
"retains the default Chromium experience" take precedence over the enhancements, and I believe blocking google assets by default on all websites will break a lot of them.

Another reason why UC doesn't do this is on desktop you can use extensions to block them if you want, but unfortunately Android versions doesn't have extensions. That is why I made the extensions support version, but it is very time consuming to maintain and still needs worked on

**Comment by NSTAdventure** [comment]
> "retains the default Chromium experience" take precedence over the enhancements, and I believe blocking google assets by default on all websites will break a lot of them.
> 
> Another reason why UC doesn't do this is on desktop you can use extensions to block them if you want, but unfortunately Android versions doesn't have extensions. That is why I made the extensions support version, but it is very time consuming to maintain and still needs being worked on

It's A Mario TIME!

**Comment by wchen342** [comment]
uBlock Origin now works most of the time, so you can use it to block trackers.

**Comment by NSTAdventure** [comment]
> uBlock Origin now works most of the time, so you can use it to block trackers.

On blockadblock 
Ads still showing bruh

**Comment by wchen342** [comment]
Wait for next version.

**Comment by NSTAdventure** [comment]
> Wait for next version.

Hey guess what?

If we disable js blockadblock.com still say wr using adblock 😮

Block ad block is very strong bruh
