### ISSUE TITLE
Req: Create Plugin To Download crx extension

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#42]
Following all your tutorial on readme.md make me stress 
Nothing is working
Visit chrome://extensions/
Will result nothing 🤦

**Comment by wchen342** [comment]
Method 1 is already using a plugin to download extensions. On what step did you have a problem?

**Comment by NSTAdventure** [comment]
> Method 1 is already using a plugin to download extensions. On what step did you have a problem?

I can't use manual method to get crx file by url :(

**Comment by wchen342** [comment]
What are you trying to achieve? The url method doesn't always work. It is easier to just install from web store.

Alternatively you can use crx downloader from some other websites.

**Comment by NSTAdventure** [comment]
> What are you trying to achieve? The url method doesn't always work. It is easier to just install from web store.
> 
> Alternatively you can use crx downloader from some other websites.

Oh yes i forgot to mention 
Add to chrome button won't appear either :-(

**Comment by wchen342** [comment]
> Add to chrome button won't appear

Can you provide a screenshot?

**Comment by NSTAdventure** [comment]
> > Add to chrome button won't appear
> 
> Can you provide a screenshot?

![IMG_20210117_074818](https://user-images.githubusercontent.com/50813528/104828118-753ae780-5898-11eb-9477-951c1ebc90ab.jpg)

...

**Comment by NSTAdventure** [comment]
@wchen342 Can You Pin This?
https://github.com/ungoogled-software/ungoogled-chromium-android/issues/44
Since Many Of Your Method On Readme.md Won't Work I Only Found Alternative Method To Download CRX File ONLY

Best Regards
NST_Adventure

**Comment by NSTAdventure** [comment]
@wchen342  man you din't mention that u should download pre release version :/
