### ISSUE TITLE
Tutorial Easy Method To Download Extension File

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#44]
Since Mostly Method On Readme.md Won't Work.
I Do Some Research And Finally Found Alternative And Easy Method To Do So:
1. Visit Chrome Webstore And crx extractor:

https://chrome.google.com/webstore/category/extensions?hl=id

https://crxextractor.com/

2. On Chrome Webstore Search And Choose (But Do Not Click Add, The Button Won't Appear) Extension That You Want To Download
3. Copy Their URL 
4. (crx extractor) Click Start For Free And Paste The Chrome Extension URL
5. (crx extractor) Click Download And Get CRX 
6. Done crx (A.K.A Extension) Is Downloaded
DISCLAIMER:
Ungoogle Chromium Currently Support Extension But In Developent Stage, Bug Crashes May Happend 
If Happend Report To Ungoogled Chromium Android Developer.
I Currently Still Find Out How To Instal Crx File From Storage Manually On Ungoogled Chromium Android

Best Regards
NST_Adventure

**Comment by wchen342** [comment]
I can not recommend a third-party website that is not developed or controled by me to users and I will not take the responsibility if the website has bugs or does any foul play

**Comment by NSTAdventure** [comment]
Yea take it as discalimer

**Comment by wchen342** [comment]
Well I can add a sentence saying "using the mentioned method or using whatever service you like to get the crx file", but I definitely won't mention the site directly.

**Comment by wchen342** [comment]
Readme has been updated.

**Comment by NSTAdventure** [comment]
> Readme has been updated.

It's A MARIO Time!
