### ISSUE TITLE
Requesting arm64 variant with extension support

### ISSUE THREAD

**Issue by hbarsaiyan** [ungoogled-software/ungoogled-chromium-android#52]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
See [ungoogled-chromium#objectives](https://github.com/Eloston/ungoogled-chromium#objectives) for a detailed list of objectives of this project. [...]

I'm not sure it's specifically in scope but at the same time not out of scope.

**Please describe the feature you would like to have**
A clear and concise description of what the problem is. [...]

arm64 variant of ungoogled-chromium with extension support.

**Describe the solution you'd like**

Prebuilt binary for arm64?

**Describe alternatives you've considered**

Using the arm variant.

**Additional context**

I don't know if #28 is still an issue but can you build arm64 variant with extension support **if possible**. And once again thanks a lot for maintaining this project :)

**Comment by wchen342** [comment]
It should be possible now with the Gandi.net servers, but they are having problems with networking on my server recently. If they can solve the problem soon then I can start to post arm64 versions too from next version.

**Comment by wchen342** [comment]
`arm64` is now released with`x86`.

**Comment by hbarsaiyan** [comment]
Thank you very much 🙏
