### ISSUE TITLE
FDroid repository link 403

### ISSUE THREAD

**Issue by dazinator** [ungoogled-software/ungoogled-chromium-android#54]
The FDroid repository link in the docs returns 403. Is there a new url?

**Comment by wchen342** [comment]
403 means forbidden. I checked the firewall log for past several hous and there are several entries, but I am not sure whether any of them is you. Several questions:

1. Are you on Tor?
2. Which client are you using?
3. If possible, what time did you access and what is the first two segments of the IP (no need to tell me full IP)?

**Comment by dazinator** [comment]
Sorry forget the 403 - I thought I could browse that repo in a web browser (i'm using chrome on a Samsung galaxy s10+) as I simply navigated to the link in the docs. That gives a 403. However adding the url to FDroid seems to work although I now have a seperate issue which is- FDroid shows the package but clicking the install button does nothing. I assume this is an FDroid issue or packaging issue due to the fact the package bundles ARM and my phone is x86. FDroid doesn't seem to handle this. Im closing this issue because its not really your problem :-)
