### ISSUE TITLE
Password Manager not Auto-fill on login pages.

### ISSUE THREAD

**Issue by junomarian** [ungoogled-software/ungoogled-chromium-android#55]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: [e.g. Realme X3]
 - OS: [e.g. Color OS Realme UI]
 - Arch: [e.g. arm64]
 - Variant: [e.g. monochrome]
 - Version: [e.g. Latest]
 
**\*Is the bug related to extensions?**
No

**\*Describe the bug**
Password Manager not Auto-fill on login pages, I am using Bitwarden Password Manager which works on Chrome, Bromite and Brave but not working on Ungoogled Chromium.

**Additional context**
I have no idea if its a bug in Password Manager or bug with UC.

**Comment by wchen342** [comment]
I thought they have fixed this? Baiscally they need to list my package name in some of their codes.

**Comment by junomarian** [comment]
> I thought they have fixed this? Baiscally they need to list my package name in some of their codes.

Ok, I got it. So it's the Password Manager. I will contact them.

**Comment by galaxyrun** [comment]
I have the same problem with Bitwarden. It does work with other browsers like firefox.
