### ISSUE TITLE
Browser crashes on closing tabs from previous session(if the tabs are closed without loading them again) 

### ISSUE THREAD

**Issue by hbarsaiyan** [ungoogled-software/ungoogled-chromium-android#59]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Lenovo Tab4 10
 - OS: LineageOS 16.0
 - Arch: arm64
 - Variant: extension
 - Version: 88.0.4324.152-2-extensions
 
**\*Is the bug related to extensions?**
Maybe 😅 I tried both arm and arm64. It happens on both.

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes/No

**\*Describe the bug**
If I open browser and close tabs from previous session without loading them again, the browser crashes. 

**\*Expected behavior**
The browser should not crash. 

**Additional context**
I have attatched the crash log.
[Log_2021-02-16_23-16-09.txt](https://github.com/ungoogled-software/ungoogled-chromium-android/files/5990579/Log_2021-02-16_23-16-09.txt)

**Comment by wchen342** [comment]
Ok I think I got what you meant. Did you mean that you were closing those tabs that are behind the first tab upon restoration? I think I reproduced that crash.

**Comment by hbarsaiyan** [comment]
> Ok I think I got what you meant. Did you mean that you were closing those tabs that are behind the first tab upon restoration? I think I reproduced that crash.

Yes that is what I meant. If I close any other tab from previous session (apart from the one loading in foreground ) the browser crashes.

**Comment by wchen342** [comment]
Ok. It was a problem I thought had been fixed. I will release an update soon.

**Comment by wchen342** [comment]
Should be fixed in 9c184f7. The release is building.
