### ISSUE TITLE
Non-functional webgl patch

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-android#60]
@csagan5 The `Add-flag-to-disable-WebGL.patch` seems to do nothing at least in `ungoogled-chromium-android`. The patch seems to only add a flag and does not change any actual code, and I tested using my version and the flag does nothing. Is it because the patch needs to work with some other patches, or it really does nothing?

**Comment by csagan5** [comment]
> I tested using my version and the flag does nothing

How did you perform this test?

> The patch seems to only add a flag and does not change any actual code

Flags named as switches set the value for such switches; I tested using `chrome://gpu` and the flag works as intended.

**Comment by wchen342** [comment]
@csagan5 I tested using [https://get.webgl.org/](https://get.webgl.org/). I re-visited the flag and found it is actually flipped, i.e. "enabled" is actually "disabled" and vice versa.

I think it is because of the naming of the flag. I assume when you "enable" "Disabling of WebGL" means WebGL shall be non-funcitonal,  but the flag seems to did it the other way around.

**Comment by csagan5** [comment]
Perhaps the flag should just say "WebGL", but the switch is `--disable-webgl`

**Comment by wchen342** [comment]
I think adding a mention of the meaning of "enable/disable" of this flag in its descrition will be good. It will make it clear when the flag is enabled then WebGL will be enabled too.

**Comment by wchen342** [comment]
Updated the description in d2331cf.

**Comment by csagan5** [comment]
@wchen342 this is how I changed the patch in Bromite: https://github.com/bromite/bromite/commit/d70bd10285fd59330c9417b88d9cb4a693f134c2#diff-b1bf5290b0cbf5f5ff4f6668b2264a78aa208a207810a20849a49dda98b9633b
