### ISSUE TITLE
The plugin needs to be reloaded

### ISSUE THREAD

**Issue by wanlyg** [ungoogled-software/ungoogled-chromium-android#65]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: xiaomi mi6
 - OS: LineageOS 18.1 (Android 11)
 - Arch: arm64
 - Variant: Extensions
 - Version: v88.0.4324.152-3
 
**\*Is the bug related to extensions?**
Yes

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes/No

**\*Describe the bug**
The plug-in fails, and the expansion page shows that it needs to be reloaded

**\*To Reproduce**
Occasionally. Seems to be related to insufficient memory when switching apps (ui died?

**\*Expected behavior**
fix bug.

**Screenshots**

**Additional context**
Plugin:uBlock Origin Violentmonkey

A similar problem occurred in an earlier version (>=83), or the problem has not been fixed

Guess, the system released the memory occupied by the plug-in, but the application did not reload

**Comment by wchen342** [comment]
It will be good if you can find a way to deterministically reproduce it.

From the description it is probably the background processes got killed but I am not sure. It will be helpful if tis can be reliably reproduced.

**Comment by wchen342** [comment]
Some additional questions:
 - Can you show me a screenshot when it needs reload?
 - Did you install using developer mode?

**Comment by wanlyg** [comment]
I did not keep the screenshots. 
I enabled developer mode, but I use online installation.
I will try to reproduce and keep the screenshot 
@wchen342

**Comment by wanlyg** [comment]
I successfully reproduced the bug
1.Open this app，Load a real web page to make the plugin active
2.Keep opening new other apps to run out of memory (The UI cannot be reloaded, but web page reloading is required
3.Return to this app, click the menu, the plug-in disappears

You may need to repeat these steps
![Screenshot_20210218-203555](https://user-images.githubusercontent.com/36926016/108358488-bf154580-7229-11eb-87d9-6c0f22332dc3.png)
![Screenshot_20210218-203444](https://user-images.githubusercontent.com/36926016/108358506-c2a8cc80-7229-11eb-9089-7976bde2e561.png)
![Screenshot_20210218-203436](https://user-images.githubusercontent.com/36926016/108358843-2af7ae00-722a-11eb-938d-176da6cad32d.png)

@wchen342

**Comment by wchen342** [comment]
Interesting. I know the icon will disappear in menu sometimes but had never seen the reload before. It is probably a complicated problem so it will take time to fix.

**Comment by wchen342** [comment]
See [https://github.com/ungoogled-software/ungoogled-chromium-android#extensions](https://github.com/ungoogled-software/ungoogled-chromium-android#extensions). I'm discontinuing extensions.
