### ISSUE TITLE
Uc Crash 

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#67]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Realme 5i
 - OS: Realme UI Android Q
 - Arch: arm 64
 - Variant: 
 - Version:
 
**\*Is the bug related to extensions?**
I don't know

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
Yes/No

**\*Describe the bug**
Closing a few tab cause uc crash and if i reopen the closed tab are comeback 

**\*To Reproduce**
1. Open uc and try create 5-6 tab 
2. Try to close some tab
3. Uc crash and when you open the closed tab are comeback

**\*Expected behavior**
No crash and comeback

**Screenshots**

**Additional context**
Is that possible some extension causing this glitch: (I Don't Know Which One If True)
-privacy badger 
-Https Everywhere
-Duck Duck Go Privacy Essentials
-ClearURL

I use This Version Of UC:
https://f-droid.org/packages/org.ungoogled.chromium.extensions.stable

Version: 88.0.4324.152 Extension

**Comment by wanlyg** [comment]
Test the last version [88.0.4324.152-3-extensions](https://github.com/ungoogled-software/ungoogled-chromium-android/releases/tag/88.0.4324.152-3-extensions) .

**Comment by NSTAdventure** [comment]
> Test the last version [88.0.4324.152-3-extensions](https://github.com/ungoogled-software/ungoogled-chromium-android/releases/tag/88.0.4324.152-3-extensions) .

Pre release have same signature?
I don't want instal clone

**Comment by wanlyg** [comment]
Yes. You should try it, it fixes some errors

**Comment by NSTAdventure** [comment]
> Yes. You should try it, it fixes some errors

 You right pre release -3 version are fix these bug 

But new bug are occurred 
Sometime extension will reloaded (Safescript)

And extension icon sometime is missing idk why
