### ISSUE TITLE
Remove Dangerous Permission

### ISSUE THREAD

**Issue by NSTAdventure** [ungoogled-software/ungoogled-chromium-android#70]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Fingerprinting is privacy issues as well i want to request remove and block finger print request at any cost due to privacy issues

**Please describe the feature you would like to have**
Finger print is privacy issues

**Describe the solution you'd like**
Remove and block finger print permission

**Describe alternatives you've considered**

**Additional context**
I use app cloner to detect dangerous permission this permission are hided and only way to manage it only via ADB Or Root Which Mean Is Dangerous To Do

**Comment by wchen342** [comment]
The permission is not on by default and it can be changed from system setting.

**Comment by NSTAdventure** [comment]
> The permission is not on by default and it can be changed from system setting.

I know but better to remove it and block their access by default due to privacy issues

I also want give another feedback for this project i will open new issues soon

**Comment by wchen342** [comment]
It is blocked by default isn't it?

I do not really want to remove it completely. I think there may be needs of it for some people. It is not something like Google tracking which there is no legistic use case.

**Comment by NSTAdventure** [comment]
@wchen342 
Finger print also used to track you that's why i request you to remove it

**Comment by wchen342** [comment]
But if you disable it from system the browser won't be able to use it. The browser cannot overwrite the system setting, it is by design.

**Comment by NSTAdventure** [comment]
> But if you disable it from system the browser won't be able to use it. The browser cannot overwrite the system setting, it is by design.

Alright and finger print should unique @wchen342

**Comment by wchen342** [comment]
What do you mean? Maybe you are confusing the fingerprint of the browser and the physical fingerprint sensor?

**Comment by NSTAdventure** [comment]
> What do you mean? Maybe you are confusing the fingerprint of the browser and the physical fingerprint sensor?

If we not block finger print at least make it unique so tracker can't track you easily like flipping hands

Learn more:
Privacytools.io

**Comment by wchen342** [comment]
Are you referring to [this part](https://privacytools.io/browsers/#fingerprint)? That is the fingerprint of the browser, and it has nothing to do with permissions.

**Comment by NSTAdventure** [comment]
> Are you referring to [this part](https://privacytools.io/browsers/#fingerprint)? That is the fingerprint of the browser, and it has nothing to do with permissions.

Yes i want the browser finger print looks unique
