### ISSUE TITLE
Add Whoogle search

### ISSUE THREAD

**Issue by hbarsaiyan** [ungoogled-software/ungoogled-chromium-android#73]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Privacy friendly google search alternative https://whoogle.tormentasolar.win/

See [ungoogled-chromium#objectives](https://github.com/Eloston/ungoogled-chromium#objectives) for a detailed list of objectives of this project. [...]

**Please describe the feature you would like to have**
A clear and concise description of what the problem is. [...]
Adding it to search options.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://github.com/benbusby/whoogle-search

**Comment by wchen342** [comment]
You can add search engines you like through `chrome://settings/search` in extension version.

**Comment by hbarsaiyan** [comment]
@wchen342 Thank you. Is there a way to enable search suggestions?

**Comment by wchen342** [comment]
That seems to be bundled with Google service so no.

**Comment by hbarsaiyan** [comment]
BTW the arm32 fdroid repo URL in readme should be https://www.droidware.info/arm/fdroid/repo?fingerprint=2144449AB1DD270EC31B6087409B5D0EA39A75A9F290DA62AC1B238A0EAAF851




21 Feb 2021, 10:01 pm by notifications@github.com:

**Comment by wchen342** [comment]
No I delibarately left that repo as it was so ppl don't need to change the link.

**Comment by wchen342** [comment]
Wait I made a mistake in the configuration. I will correct it now.
