### ISSUE TITLE
Remove AMP from Google search results

### ISSUE THREAD

**Issue by Balachandarsmr** [ungoogled-software/ungoogled-chromium-android#75]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
Google's AMP is not made to improve speed, but ad revenue. One of the problems with the Accelerated Mobile Pages concept is that content built utilizing AMP is served up through a cache on Google’s server rather than actually linking to the original page on a publisher’s website. This means that the reader is spending more time on Google’s site and will be seeing Google advertising as opposed to any paid advertising on the content provider’s site. More money for Google, less money for the actual content creator.

**Please describe the feature you would like to have**
Please kill amp in Google search results. Some sites don't display all contents in amp version. Example reddit
![Screenshot_20210223_115908](https://user-images.githubusercontent.com/29444683/108809363-b11b4800-75ce-11eb-8982-0acb140f9bad.jpg)

**Describe the solution you'd like**
Bromite has amp removal patch

**Describe alternatives you've considered**
Google don't give amp results in desktop useragent 

**Additional context**

**Comment by wchen342** [comment]
I can add the bromite patch next version.

**Comment by wchen342** [comment]
Added in ca5cf4b.
