### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by chromer030** [ungoogled-software/ungoogled-chromium-android#77]
**Please explain why your feature request fall into the scope of ungoogled-chromium?**
It relate to privacy and restrict-less and safe internet access.

**Please describe the feature you would like to have**
Please add support for proxy setting, none of extensions in Web Store working in android, all failing.

**Describe the solution you'd like**
Add proxy support so extensions could use this feature.

**Describe alternatives you've considered**
Use Bromite's proxy feature, a complete and feature-rich page in settings to set any proxy.

**Additional context**

**Comment by wchen342** [comment]
This inclusion seems reasonable, I will add the Bromite patch.

**Comment by wchen342** [comment]
Added in ca5cf4b.
