### ISSUE TITLE
Reformation of project

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium-android#78]
Following the discussion in [Bromite](https://github.com/bromite/bromite/discussions/957#discussioncomment-413624), I will likely make the following changes in the near future:

 - Remove certain features in the plain version of `ungoogled-chromium-android` and focus only on the removal of Google services
 - Stop maintaining the extension support patches and move them to a sperate repository, so that anyone interested can fork it and continue the work. I understand it may be a disappointment, but from my experience I realized it is too much work for an individual to maintain, and I felt it is impossible for me to maintain it in long term.

In the future I will probably devote more time to help improve Bromite. The main goal of `ungoogled-chromium`, which is the removal of Google services, has been achieved some time ago.
I will keep maintaining the base version.

**Comment by DarknessKiller123** [comment]
Well, that's sad. I recently found the project and with extensions it was the best. Two questions,  Will you support Bromite from now?, Is any possibility of returning the proyect?

**Comment by wchen342** [comment]
@DarknessKiller123

> Will you support Bromite from now?

Bromite doesn't think extensions fit in its scope per [this comment](https://github.com/bromite/bromite/discussions/957#discussioncomment-413618).

> Is any possibility of returning the proyect?

Unless there are enough interests that make people start contributing to the project. Adding the extension menu items alone took me almost 100 hours of work, and API fixes and the initial support took similar amount of work. I simply cannot keep doing that for long.

**Comment by NSTAdventure** [comment]
@wchen342 
i was hope you consider this some user like me are rallying on extension every single day
also i don't trust other browser like MSE

they do support extension but microsoft track every your move

**Comment by wchen342** [comment]
I understand that you may need the extensions. However please also consider the fact that these projects are done by me sacrificing my free time using my own resources. I am not a company and I do not make profits from this. Besides contributing to open source projects I have other works to do in order to feed myself, and I also have other things I wish to do in my free time because it is my life. As I stated above it's a problem about limited time I have, and I simply cannot afford putting that much amount of time into this anymore.

To put it in a mild way, when asking for something, please consider other people's situation not just your own. To say it in a more straight forward way, that I have no obligation for any of these because there is nothing binding here, only vonlunteered contributions. Of course I will try to do my best to provide something good, but that does not mean I *have to*.

**Comment by NSTAdventure** [comment]
> I understand that you may need the extensions. However please also consider the fact that these projects are done by me sacrificing my free time using my own resources

I understand 




> To say it in a more straight forward way, that I have no obligation for any of these because there is nothing binding here, only vonlunteered contributions. Of course I will try to do my best to provide something good, but that does not mean I _have to_.

I not force you to do what i want 

Hey i am not A greedy bro


But do you Will add extension feature in next update? Even extension feature not updated anymore?

**Comment by wchen342** [comment]
> But do you Will add extension feature in next update? Even extension feature not updated anymore?

No and yes.

**Comment by NSTAdventure** [comment]
> > But do you Will add extension feature in next update? Even extension feature not updated anymore?
> 
> No and yes.

I hope you add It Is ok they not updated but most important they added yay :D

**Comment by wchen342** [comment]
> they not updated but most important they added

The chromium codes changes between versions so old patches cannot be used on newer versions. It takes time to adapt all the patches to new version.
