### ISSUE TITLE
TriChrome Builds Broken Again

### ISSUE THREAD

**Issue by lazerl0rd** [ungoogled-software/ungoogled-chromium-android#83]
**\*Device info (please complete the following information):**
 - Device: Google Pixel 5
 - OS: ProtonAOSP 11.3.3
 - Arch: arm64
 - Variant: TriChrome
 - Version: 89.0.4389.90
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
Ungoogled Chromium doesn't appear in the app drawer and WebView isn't registering.

**\*To Reproduce**
1. Install the TriChrome variants of v89.0.4389.82-1 or v89.0.4389.90-1.

**\*Expected behavior**
The browser appearing in the app drawer and WebView being registered.

**Screenshots**
n/a

**Additional context**
v88.0.4324.182-2 works fine.

**Comment by wchen342** [comment]
The cert seems right on the apks, not sure what was going on. Will try to investigate when building next version.

**Comment by wchen342** [comment]
Can you try the following:

 - `adb shell 'dumpsys package | grep "Package \["' | grep trichromelibrary`. You shall get a package name like `org.chromium.trichromelibrary_[some random number]`.
 - `adb uninstall org.chromium.trichromelibrary_[the random number]`
 - install the two trichrome apks again

**Comment by wchen342** [comment]
The problem is more complicated than I thought, there is a unknown problem with gn files.
If possible please use `ChromeModernPublic` for now. This will take some time to fix.

**Comment by lazerl0rd** [comment]
89.0.4389.114-2 successfully fixed the TriChrome build of Chrome, however WebView still fails to install with the error shown below:

![](https://user-images.githubusercontent.com/24303423/114804260-f53df400-9d98-11eb-8861-64075775a250.png)

And yes, I've installed 89.0.4389.114-2's TriChrome library.

PS: Is it not possible to build all TriChrome targets (in other words, WebView along with Library and Chrome)? Your TriChromeWebView builds have been unusually large and I suspect this is due to not being built alongside the relevant TriChromeLibrary. The current build of TriChromeWebView is around 100MB, which seems that code code from the library isn't being used).

**Comment by wchen342** [comment]
The webview is bigger probably because I turned off split modules to make extracted universal apk work. For `Trichrome` and `ChromeModern` now only have bundle targets which can only build `aab` files not `apk`, which means either I extract an universal apk with bundletool or you have to install `aab` files yourself with bundletool. The apk target for webview still exists so I will try turn on split modules and build again.

Webview cannot find library most likely because I changed library to be pure 64 bit but webview is built towards normal target. Can you try [this library](https://uc.droidware.info/tmp/TrichromeLibrary.apk) and see whether it works for webview? I cannot debug it locally because custom webview seems to not work on emulators.

**Comment by lazerl0rd** [comment]
> The webview is bigger probably because I turned off split modules to make extracted universal apk work. For `Trichrome` and `ChromeModern` now only have bundle targets which can only build `aab` files not `apk`, which means either I extract an universal apk with bundletool or you have to install `aab` files yourself with bundletool. The apk target for webview still exists so I will try turn on split modules and build again.

I see, thanks for your swift response.

> Webview cannot find library most likely because I changed library to be pure 64 bit but webview is built towards normal target. Can you try [this library](https://uc.droidware.info/tmp/TrichromeLibrary.apk) and see whether it works for webview? I cannot debug it locally because custom webview seems to not work on emulators.

This library works, yeah. I assume you plan  on building the next TriChromeWebView as pure 64-bit (at least for arm64)?

In terms of testing it on an emulator, I may have an idea but I'll need to get back to you on that one in a few days (feel free to shoot me an email if I forget).

**Comment by wchen342** [comment]
Can you try the new version and see whether it works?

Also I noticed I never had the right signatures on the trichrome version of webview. I will update a signed version soon and let me know whether it breaks the installation.

**Comment by lazerl0rd** [comment]
> Can you try the new version and see whether it works?
> 
> Also I noticed I never had the right signatures on the trichrome version of webview. I will update a signed version soon and let me know whether it breaks the installation.

It works now, thanks. I'm also glad the size of WebView has shrunk down, alongside it being 64-bit.
