### ISSUE TITLE
Don't know if this is a bug but I can't change my "Webview implementation" on android 11

### ISSUE THREAD

**Issue by Michael82548** [ungoogled-software/ungoogled-chromium-android#84]
I have tried to disable the default android system WebView but that did not work. It shows as the only option still. I even tried bromine but that also did not work. Is there anything that I am doing wrong here?

**Comment by Yonle** [comment]
Same issue at Android 8, Vivo 1820

**Comment by wchen342** [comment]
Android 8 should work. Try the method in [Bromite wiki](https://github.com/bromite/bromite/wiki/Installing-SystemWebView).
I'm not sure Android 11, they probably changed something. This is not a problem I can fix on my side because it is an OS limitation. Maybe asking on XDA.

**Comment by Michael82548** [comment]
I just realized that the device may have to be rooted

**Comment by wchen342** [comment]
Yes you need a rooted device normally.

**Comment by Yonle** [comment]
But if you still want try it without root, Download apps called [F1 VM](https://f1vm.com) and set the webview as Ungoogled Webview after moving Ungoogled Webview apps to System.

**Comment by lazerl0rd** [comment]
> I have tried to disable the default android system WebView but that did not work. It shows as the only option still. I even tried bromine but that also did not work. Is there anything that I am doing wrong here?

WebView, generally, two requirements on Android:

1) The WebView being a system application (as in, either at `/system/app` or `/system/priv-app`).

2) The WebView provider being in the list of verified providers, and if a signature is provided alongside it's reference in the list - making sure the signature matches up.

1) pretty much requires root access or for you to break AVB and modify your system image. For 2), you need to build and install a config overlay (which basically needs to also be in `/system` and therefore also requires root access).
