### ISSUE TITLE
Cannot access chrome://settings

### ISSUE THREAD

**Issue by badochov** [ungoogled-software/ungoogled-chromium-android#86]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Poco F2 Pro
 - OS: Lineage OS 18.1
 - Arch: arm64
 - Variant: dunno installed from fdroid
 - Version: 89.0.4389.114
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
Going to chrome://settings or chrome://settings/search results in "This site can't be reached" error page.

**\*To Reproduce**
1. Go to chrome://settings or chrome://settings/search
2. See error

**\*Expected behavior**
Settings should open.

**Comment by wchen342** [comment]
`chrome://settings` is only available on desktop versions, Android version doesn't have them.

**Comment by badochov** [comment]
But in one of previous issue on how to set other search engine [issuee](https://github.com/ungoogled-software/ungoogled-chromium-android/issues/73) got reponse to go to chrome://settings/search. So how can one set custom search engine when extensions version is no longer supported.

BTW why did extension version got discontinueed?

**Comment by wchen342** [comment]
The settings page was a side-effect of enabling extensions, so it doesn't exist one the usual version.

> BTW why did extension version got discontinueed?

Because the amount of work is prohibitive for me to do alone.
