### ISSUE TITLE
Videos cannot be played

### ISSUE THREAD

**Issue by Flashbin** [ungoogled-software/ungoogled-chromium-android#88]
Please at least answer all questions marked with * below. Issues without answering these questions will be closed.

**\*Device info (please complete the following information):**
 - Device: Samsung Galaxy S10 (SM-G973F)
 - OS: Android 11 with One UI 3.1
 - Arch: ARMv8.2-A AArch64
 - Variant: F-Droid
 - Version: 90.0.4430.93 but also the previous 89. version
 
**\*Is the bug related to extensions?**
No

**\*If not related to extensions, can the bug be reproduced with corresponding Chromium version?**
No

**\*Describe the bug**
Any video (for example Youtube) will just be white. The player will still be shown, but the video is just white. Sound works.

**\*To Reproduce**
1. Go to any video, for example Youtube
2. See error

**\*Expected behavior**
Expect the video to be played and shown properly.

**Screenshots**
![Screenshot_20210513-120106_Ungoogled Chromium](https://user-images.githubusercontent.com/63650660/118110972-5cc08100-b3e3-11eb-8f45-1443c7fbe9fc.png)

**Additional context**
None.

**Comment by wchen342** [comment]
Usually it's hardware acceleration related. Can you try enabling/disabling hardware acceleration/GPU related flags in `chrome://flags` and see whether some of them will fix the problem?

**Comment by Flashbin** [comment]
Disabling ``Hardware-accelerated video decode`` fixed the problem, thanks!

**Comment by Flashbin** [comment]
@wchen342 Ah sorry, celebrated too soon. It fixed it on Youtube, but not on other sites, for example Twitter. I've also tried other hardware acceleration flags, but none helepd.

**Comment by wchen342** [comment]
Seems to be the same problem as bromite/issues/1005. Will update the patch next version.

**Comment by wchen342** [comment]
The temporary solution is to dosable vulkan or enable the AIMageReader flag.

**Comment by wchen342** [comment]
A new version has been published. Please try and see whether it fixes the problem.

**Comment by Flashbin** [comment]
@wchen342 Version 90.0.4430.212 fixes the issue, works on Youtube and Twitter with HW-Acceleration enabled. Thanks!
