### ISSUE TITLE
Fdroid version question

### ISSUE THREAD

**Issue by Fehertukor** [ungoogled-software/ungoogled-chromium-android#91]
Hi!
I really like your work but the Fdroid version
Ungoogled Chromium Extensions (A lightweight approach to removing Google web service dependency) - https://f-droid.org/packages/org.ungoogled.chromium.extensions.stable

did not updated a long ago.
Which one should I download from GitHub to update it?

Thaks!

**Comment by wchen342** [comment]
The extension version was [discontinued](https://github.com/ungoogled-software/ungoogled-chromium-android/issues/78).
