### ISSUE TITLE
QR codes cannot be scanned

### ISSUE THREAD

**Issue by mealwhiles** [ungoogled-software/ungoogled-chromium-android#93]
I expect this might have something to do with requiring a Google API to interpret QR codes. If so, I understand why the feature doesn't work. 

Here's some pertinent info:
 - Device: LG XCharge (LGE LG-M322)
 - OS: Android 7.0
 - Arch: arm64
 - Version: v91.0.4472.77-1
 - Bug not related to extensions

To reproduce the bug:
1. Open a webpage in Ungoogled Chromium Android
2. tap the three dots in the top-right
3. Tap Share...
4. Tap QR code
5. Tap scan at the top
6. Attempt to scan a QR code

Expected behavior:
The QR code is scanned and opens a webpage.

Actual behavior:
The camera view appears as expected, but the code is never scanned.
No error messages are given, but no QR code can be scanned.

More context:
Scanning QR codes works on Firefox and using an app called Binary Eye.
Therefore I know the problem is not caused by my OS or bad camera quality.

**Comment by wchen342** [comment]
Yes, you assumption is right. The QR scanning are removed because it uses google's vision API which depends on a binary library.
