### ISSUE TITLE
link for download perbuild sdk ndk zips case error

### ISSUE THREAD

**Issue by george5613** [ungoogled-software/ungoogled-chromium-android#94]
in build.sh found link for download perbuild sdk ndk zips but case error.

sdk_link="https://android-rebuilds.beuc.net/dl/bundles/android-sdk_eng.11.0.0_r27_linux-x86.zip"
sdk_tools_link="https://android-rebuilds.beuc.net/dl/repository/sdk-repo-linux-tools-26.1.1.zip"
ndk_link="https://android-rebuilds.beuc.net/dl/repository/android-ndk-r20b-linux-x86_64.tar.bz2"

seem link is broken

**Comment by wchen342** [comment]
I have [asked upstream about it](https://gitlab.com/android-rebuilds/auto/-/issues/3) but got no reply. I will remove the links.

**Comment by wchen342** [comment]
Fixed in bcd67d7.
