### ISSUE TITLE
droidware connection

### ISSUE THREAD

**Issue by fusionneur** [ungoogled-software/ungoogled-chromium-android#95]
On android, the app constantly tries to connect to uc.droidware.info. How can i disable this (i can't find any setting) and why is it necessary in the first place?

**Comment by wchen342** [comment]
I thought I have disabled it by default? It was added for people wanted a new version update notice. Can you check `enable-inline-update-flow` is enabled or not?

**Comment by fusionneur** [comment]
in chrome://flags it is set to default (v 91.0.44721.114)

**Comment by wchen342** [comment]
Can you check whether set it to `disabled` stops the connection?

**Comment by fusionneur** [comment]
it does not  stop it (i also forced stopped and relaunched the app)

**Comment by wchen342** [comment]
Seems to be a bug on the flag. Chromium removed the flag some time ago and the condition guarding the update must be changed. I will fix it next version.

**Comment by wchen342** [comment]
Fixed in bcd67d7.
