### ISSUE TITLE
Issues with #enable-gpu-rasterization flag on

### ISSUE THREAD

**Issue by griffi-gh** [ungoogled-software/ungoogled-chromium-android#97]
**Video:**   

[https://streamable.com/ajqr39](https://streamable.com/ajqr39)

**had this issue on these websites:** 

[Discord Support](https://support.discord.com/hc/en-us/community/posts/360031101592-Increase-max-file-size-for-free-accounts)    
[Quora](https://www.quora.com/In-the-video-game-Factorio-what-is-the-best-way-to-protect-your-factory-from-the-aliens)

**Device:**  Xiaomi MI Play  
Ungoogled Chromium 92.0.4515.107 (F-Droid)    
Android 8.1.0 O11019 (MIUI 11.0.3 OFIMIXM Stable (Stock))    

It works fine on ungoogled-chromium 89 and stock chrome 92.

**Comment by griffi-gh** [comment]
huh it randomly started working again when i wanted to check the logcat.
Strange

**Comment by wchen342** [comment]
Maybe try `AImageReaderMediaPlayer` in flags? Also you can try enabling Vulkan on Android, maybe it will solve the problem.

**Comment by griffi-gh** [comment]
it still occurs occasionally.  
^ my phone doesn't support vulkan

**Comment by wchen342** [comment]
Without more information it is hard to say. Can you post your `chrome://gpu`? Try to get logs when it happens may be helpful too. Also try search the chromium issue tracker to see whether something similar has been reported.

**Comment by griffi-gh** [comment]
Graphics Feature Status
Canvas: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Disabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Rasterization: Software only. Hardware acceleration disabled
Skia Renderer: Enabled
Surface Control: Disabled
Video Decode: Hardware accelerated
Vulkan: Disabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
avoid_one_component_egl_images
clear_uniforms_before_first_program_use
dont_delete_source_texture_for_egl_image
exit_on_context_lost
force_enable_color_buffer_float_except_rgb32f
max_msaa_sample_count_4
max_texture_size_limit_4096
remove_dynamic_indexing_of_swizzled_vector
unbind_fbo_on_context_switch
use_virtualized_gl_contexts
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
disabled_webgl_extension_EXT_disjoint_timer_query
disabled_webgl_extension_EXT_disjoint_timer_query_webgl2
Problems Detected
Surface Control has been disabled by Finch trial or command line.
Disabled Features: surface_control
Raster is using a single thread.
Disabled Features: multiple_raster_threads
Accelerated rasterization has been disabled, either via blocklist, about:flags or the command line.
Disabled Features: rasterization
Imagination drivers are buggy with context switching: 230896
Applied Workarounds: unbind_fbo_on_context_switch
Share group-related crashes and poor context switching perf on Imagination drivers
Applied Workarounds: use_virtualized_gl_contexts
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Limit max texure size to 4096 on all of Android
Applied Workarounds: max_texture_size_limit_4096
eglCreateImageKHR fails for one component textures on PowerVR: 579060, 632461
Applied Workarounds: avoid_one_component_egl_images
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Don't expose disjoint_timer_query extensions to WebGL unless site isolation is enabled: 808744
Limit MSAA to 4x on Android devices: 797243
Applied Workarounds: max_msaa_sample_count_4
Context lost recovery often fails on PowerVR Rogue GE8* GPUs on Android.: 942106
Applied Workarounds: exit_on_context_lost
Remove dynamic indexing for swizzled vectors on Android: 709351
Applied Workarounds: remove_dynamic_indexing_of_swizzled_vector
Some drivers seem to require as to use original texture whenever possible: 1052114, 1117370
Applied Workarounds: dont_delete_source_texture_for_egl_image
Always assume float formats are renderable on Android except RGB32F: 1127387
Applied Workarounds: force_enable_color_buffer_float_except_rgb32f
Version Information
Data exported	2021-08-20T23:02:16.550Z
Chrome version	Chrome/92.0.4515.107
Operating system	Android 8.1.0
Software rendering list URL	https://chromium.9oo91esource.qjz9zk/chromium/src/+/92.0.4515.107/gpu/config/software_rendering_list.json
Driver bug list URL	https://chromium.9oo91esource.qjz9zk/chromium/src/+/92.0.4515.107/gpu/config/gpu_driver_bug_list.json
ANGLE commit id	6714781d1502
2D graphics backend	Skia/92 a77a4620d2fbe22ca41d1b96c1d92864c6a9ef8e
Command Line	--use-mobile-user-agent --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5 --use-mobile-user-agent --enable-viewport --validate-input-event-stream --enable-longpress-drag-selection --touch-selection-strategy=direction --main-frame-resizes-are-orientation-changes --disable-composited-antialiasing --enable-dom-distiller --flag-switches-begin --enable-experimental-web-platform-features --disable-gpu-rasterization --enable-quic --fingerprinting-canvas-image-data-noise --enable-features=ChromeShareLongScreenshot,DnsHttpssvc,InsecureFormSubmissionInterstitial,PasswordImport,Portals,TabGridLayoutAndroid,TabGroupsContinuationAndroid,TabSwitcherOnReturn:tab_switcher_on_return_time_ms/1800000,UserMediaScreenCapturing,WebBundles,WebPaymentsExperimentalFeatures --flag-switches-end --top-controls-show-threshold=0.5 --top-controls-hide-threshold=0.5
Driver Information
Initialization time	341
In-process GPU	false
Passthrough Command Decoder	false
Sandboxed	false
GPU0	VENDOR= 0x0000 [Imagination Technologies], DEVICE=0x0000 [PowerVR Rogue GE8320] *ACTIVE*
Optimus	false
AMD switchable	false
Driver vendor	
Driver version	1.9
GPU CUDA compute capability major version	0
Pixel shader version	3.20
Vertex shader version	3.20
Max. MSAA samples	4
Machine model name	MI PLAY
Machine model version	
GL_VENDOR	Imagination Technologies
GL_RENDERER	PowerVR Rogue GE8320
GL_VERSION	OpenGL ES 3.2 build 1.9@4971894
GL_EXTENSIONS	GL_EXT_debug_marker GL_ANDROID_extension_pack_es31a GL_EXT_blend_minmax GL_EXT_buffer_storage GL_EXT_clear_texture GL_EXT_color_buffer_float GL_EXT_conservative_depth GL_EXT_copy_image GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_draw_buffers_indexed GL_EXT_draw_elements_base_vertex GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_EXT_gpu_shader5 GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_polygon_offset_clamp GL_EXT_primitive_bounding_box GL_EXT_pvrtc_sRGB GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_group_vote GL_EXT_shader_io_blocks GL_EXT_shader_non_constant_global_initializers GL_EXT_shader_pixel_local_storage GL_EXT_shader_pixel_local_storage2 GL_EXT_shader_texture_lod GL_EXT_sparse_texture GL_EXT_sRGB_write_control GL_EXT_tessellation_point_size GL_EXT_tessellation_shader GL_EXT_texture_border_clamp GL_EXT_texture_buffer GL_EXT_texture_cube_map_array GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_sRGB_decode GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_EXT_YUV_target GL_IMG_bindless_texture GL_IMG_framebuffer_downsample GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_compression_pvrtc2 GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_draw_buffers_indexed GL_OES_draw_elements_base_vertex GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_get_program_binary GL_OES_gpu_shader5 GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL_OES_rgb8_rgba8 GL_OES_sample_shading GL_OES_sample_variables GL_OES_shader_image_atomic GL_OES_shader_io_blocks GL_OES_shader_multisample_interpolation GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_tessellation_point_size GL_OES_tessellation_shader GL_OES_texture_border_clamp GL_OES_texture_buffer GL_OES_texture_cube_map_array GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float GL_OVR_multiview GL_OVR_multiview2 GL_OVR_multiview_multisampled_render_to_texture
Disabled Extensions	GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions	EXT_disjoint_timer_query EXT_disjoint_timer_query_webgl2
Window system binding vendor	
Window system binding version	
Window system binding extensions	
Direct rendering version	unknown
Reset notification strategy	0x8252
GPU process crash count	0
gfx::BufferFormats supported for allocation and texturing	R_8: not supported, R_16: not supported, RG_88: not supported, BGR_565: not supported, RGBA_4444: not supported, RGBX_8888: not supported, RGBA_8888: not supported, BGRX_8888: not supported, BGRA_1010102: not supported, RGBA_1010102: not supported, BGRA_8888: not supported, RGBA_F16: not supported, YVU_420: not supported, YUV_420_BIPLANAR: not supported, P010: not supported
Compositor Information
Tile Update Mode	One-copy
Partial Raster	Enabled
GpuMemoryBuffers Status
R_8	Software only
R_16	Software only
RG_88	Software only
BGR_565	GPU_READ, SCANOUT
RGBA_4444	Software only
RGBX_8888	GPU_READ, SCANOUT
RGBA_8888	GPU_READ, SCANOUT
BGRX_8888	Software only
BGRA_1010102	Software only
RGBA_1010102	Software only
BGRA_8888	Software only
RGBA_F16	Software only
YVU_420	Software only
YUV_420_BIPLANAR	Software only
P010	Software only
Display(s) Information
Info	Display[0] bounds=[0,0 393x830], workarea=[0,0 393x830], scale=2.75, rotation=0, panel_rotation=0 external.
Color space (all)	{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}
Buffer format (all)	RGBA_8888
SDR white level in nits	100
Bits per color component	8
Bits per pixel	24
Video Acceleration Information
Encode h264 baseline	0x0 to 1280x720 pixels, and/or 30.000 fps
Vulkan Information
Device Performance Information

**Comment by wchen342** [comment]
`Accelerated rasterization has been disabled, either via blocklist, about:flags or the command line.`

This looks strange. What's you `chrome://version` output? If there is no flag disabling hardware acceleration then I feel like it is related to hardware.

**Comment by griffi-gh** [comment]
^ i disabled hardware acceleration in flags because as i said it's  very glitchy

**Comment by griffi-gh** [comment]
i can resend the chrome://gpu info with it enabled if needed

**Comment by griffi-gh** [comment]
oh, why is skia on in chrome:gpu? it never worked properly on my device!

**Comment by wchen342** [comment]
> why is skia on in chrome:gpu?

All Google products' UI are based on Skia/ANGLE. Including Chromium and Flutter. If your phone has problem with the whole pibrary then it seems you will have a better luck trying to report this to Google to see whether they know more about it.
